name: lpres
version: 0.1.0
date: 09/03/2016
description: Nilpotent Quotients of L-Presented Groups

authors:
    - name: René Hartung

maintainers:
    - name: Laurent Bartholdi
      url: http://www.uni-math.gwdg.de/laurent

GAP: ">= 4.4"

needed-pkgs:
    - name: "polycyclic"
      version: ">= 2.5"
      url: "http://www.icm.tu-bs.de/ag_algebra/software/polycyclic/"
    - name: "FGA"
      version: ">= 1.1.0.1"
      url: "http://www.icm.tu-bs.de/ag_algebra/software/FGA/"

suggested-pkgs:
    - name: "ParGAP"
      version: ">= 1.1.2"
      url: "http://www.gap-system.org/HostedGapPackages/pargap/"
    - name: "AutPGrp"
      version: ">= 1.4"
      url: "http://www.icm.tu-bs.de/~beick/so.html"
    - name: "ACE"
      version: ">= 5.0"

www: https://laurentbartholdi.github.io/lpres
readme: https://laurentbartholdi.github.io/lpres/README
packageinfo: https://laurentbartholdi.github.io/lpres/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/laurentbartholdi/lpres/releases/download/v0.1.0/lpres-0.1.0.tar.gz

abstract: The NQL Package defines new GAP objects to work with L-presented groups. The main part of the package is a nilpotent quotient algorithm for L-presented groups. That is an algorithm which takes as input an L-presented group L and a positive integer c. It computes a polycyclic presentation for the lower central series quotient L/gamma_c(L).

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
